name: Tests
on:
  - push
  - pull_request


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # 3.9 is unofficially supported but not tested against because it is
          # not supported by JAX + FINUFFT
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
           version: "0.4.26"
           #enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Install package
        run: uv pip install -e .

      - name: "Install jax extras"
        run: uv pip install "jax<0.6" jax-finufft

      #- name: "Run tests"
      #  run: |
      #    uv run pytest -x -v tests --cov-report lcov:coverage.info

      - name: "Install Coveralls"
        run: uv pip install coveralls

      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run coverage run --source=src/ -m pytest tests/
          uv run coveralls
